### ISSUE TITLE
ctp-linux64-6.3.5-1.2.jar，这个jar在mvn仓库中没有。

### ISSUE THREAD

**Issue by wzjin** [zjulzq/javacpp4ctp-demo#3]
ctp-linux64-6.3.5-1.2.jar，这个jar在mvn仓库中没有。

**Comment by zjulzq** [comment]
@wzjin 啊？居然有朋友光临我的这个小项目，真是荣幸。这几个jar包是我封装出来的，需要使用maven命令单独安装。你能简单描述下你的需求吗？看看我能不能帮到你。

**Comment by wzjin** [comment]
我在qq上和你聊。
